name: Deploy-Lambda-Python

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "**/*.py"
      - "**/deploy_lambda.yml"

permissions:
  id-token: write
  contents: read
defaults:
  run:
    working-directory: "./hello_lambda"
env:
  PYTHON_VERSION: 3.13
  function-name: hello_lambda_actions
  lambda-role-arn: ${{ secrets.LAMBDA_ROLE_ARN }}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Build
        run: pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy Lambda
        uses: aws-actions/aws-lambda-deploy@v1.0.1
        with:
          function-name: ${{ env.function-name }}
          code-artifacts-dir: ./hello_lambda
          handler: app.lambda_handler
          runtime: python${{ env.PYTHON_VERSION }}
          role: ${{ env.lambda-role-arn }}
          dry-run: false
